# Generated by Django 3.2.8 on 2021-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='item_id_number',
            field=models.CharField(default='One', max_length=20),
        ),
    ]
