# Generated by Django 3.2.8 on 2021-11-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211120_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date_added']},
        ),
    ]
