# Generated by Django 3.2.8 on 2021-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterregister',
            options={'ordering': ['email']},
        ),
    ]
