# Generated by Django 3.2.8 on 2021-11-24 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_newsletterregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterregister',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='newsletterregister',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
